### ISSUE TITLE
How do i know it's working?

### ISSUE THREAD

**Issue by helderribeirosousa** [nicolopignatelli/wc2018-slack-bot#2]
Hey there,

i was able to compile the bot. Now i've started it with the required environment variables but nothing happens. Should i expect any output, or should i've wait for a match to begin?

**Comment by helderribeirosousa** [comment]
I was starting the bot with the wrong type of token. The type of token you need is a "Legacy Token". Once you start it with a legacy token as env variable 'WC2018-SLACK-TOKEN' it will post in the designated channel.

**Comment by nicolopignatelli** [comment]
Hi, thanks for asking.
I didn't use a Legacy Token.

What I did
I clicked Add Configuration in /apps/manage/custom-integrations -> Bots and used the generated API Token
