### ISSUE TITLE
Bot keeps spamming the channel when there are two matches at the same time

### ISSUE THREAD

**Issue by d6o** [nicolopignatelli/wc2018-slack-bot#6]
![image](https://user-images.githubusercontent.com/683170/41858179-7fcf06ea-7899-11e8-8477-38596ede1bee.png)

**Comment by myoung34** [comment]
Big time

https://imgur.com/a/vP6SjU3
https://imgur.com/a/2eZJIHD

**Comment by nicolopignatelli** [comment]
I noticed. I was under the assumption that the WC2018 schedule had no concurrent matches. I'll fix that as soon as I can.

**Comment by estiens** [comment]
Thanks for fixing this so quick! Worked a treat!

FYI, if you are interested in spitting out more info at the start of the match could now do things like starting 11 for each time, weather conditions, attendance, etc

Works great in our slack at work, makes me less sad to be missing matches!

**Comment by nicolopignatelli** [comment]
We use it at work for the same purpose :)

Thanks for the suggestion, I'll look again at the API and see what I can add.
